### ISSUE TITLE
Error: Invalid or corrupt jarfile 

### ISSUE THREAD

**Issue by jbadeau** [khalilou88/jnxplus#338] opened 2023-07-20 10:08 UTC
I have tried yarn install using node 18 and 20 with the following dependencies on mac and unix 

```json
{
  "private": true,
  "devDependencies": {
    "@jnxplus/nx-maven": "0.6.4",
    "@jnxplus/nx-boot-maven": "7.2.3",
    "@nx/workspace": "16.5.3",
    "nx": "16.5.3"
  }
}

```

I get the following error:

```
error /Users/jbadeau/git/techx/node_modules/@jnxplus/nx-boot-maven: Command failed.
Exit code: 1
Command: node src/scripts/install-linters.js
Arguments: 
Directory: /Users/jbadeau/git/techx/node_modules/@jnxplus/nx-boot-maven
Output:
Error: Invalid or corrupt jarfile /Users/jbadeau/git/techx/node_modules/@jnxplus/tools/linters/ktlint/ktlint
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: java -jar /Users/jbadeau/git/techx/node_modules/@jnxplus/tools/linters/ktlint/ktlint --version
Error: Invalid or corrupt jarfile /Users/jbadeau/git/techx/node_modules/@jnxplus/tools/linters/ktlint/ktlint

    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at isAnotherVersion (/Users/jbadeau/git/techx/node_modules/@jnxplus/common/src/lib/utils/index.js:94:53)
    at /Users/jbadeau/git/techx/node_modules/@jnxplus/common/src/lib/utils/index.js:85:18
    at Generator.next (<anonymous>)
    at /Users/jbadeau/git/techx/node_modules/@jnxplus/common/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/jbadeau/git/techx/node_modules/@jnxplus/common/node_modules/tslib/tslib.js:163:16)
    at getKtlintPath (/Users/jbadeau/git/techx/node_modules/@jnxplus/common/src/lib/utils/index.js:67:20) {

```

I have checked the dir and the jar is not downloaded. Works when the @jnxplus/nx-boot-maven plugin is removed but we use both.

**Comment by jbadeau** [comment] 2023-07-20 16:11
Basically both plugins work alone but not together

**Comment by khalilou88** [comment] 2023-07-21 11:12
Yes we can't use both plugins in the same time. Also we can't add both to to NX.json file.

Nx-maven is still in active development. I want to change how build and serve executor works. I want to add command option so we can know which command we are using with maven. I will remove framework option too. You can check pull request to know more.

Nx-maven is the future but need to fix all mismatch between frameworks.

**Comment by khalilou88** [comment] 2023-07-28 16:18
@jbadeau I will close this as it's not a bug. `Nx-maven` is more a replacement for `nx-boot-maven` in the future.

**Closed** 2023-07-28 16:19 UTC

**Comment by khalilou88** [comment] 2023-08-21 16:28
@jbadeau Now Nx-maven is a replacement for nx-boot-maven. Working to update docs
