### ISSUE TITLE
NX Maven caching

### ISSUE THREAD

**Issue by jbadeau** [khalilou88/jnxplus#294] opened 2023-06-27 21:57 UTC
Hello,

I have noticed that nx maven artifact caching prob has an issue.

Given I have a dependency where app-a depends on lib-b. When I run a Nx cached build the lib-b target folder will be replaced but the lib-b wont be installed to the local m2 repo. Hence if app app-a is not cached then it will fail to build as maven wont see lib-b in the local repo.

**Comment by jbadeau** [comment] 2023-06-28 14:32
We have our own maven plugin where we call the install plugin directly via a target called install-install:

```bash
mvn jar:jar install:install -pl apps/myapp
```

which basically pushes the jar/war/ear/pom to the local repository. This target must never be cached as it needs to actually publish to the local repo

**Comment by jbadeau** [comment] 2023-06-28 16:40
That won’t work because the output of the target needs to be the local npm repo which is not easy or even possible to calculate.

**Comment by jbadeau** [comment] 2023-06-28 16:41
The target has to be told to put the output in the m2 but this path contains the version which is dynamic

**Comment by jbadeau** [comment] 2023-06-28 16:42
Basically this operation should not be catchable but I see that I can use your plugin to create execute it

**Comment by jbadeau** [comment] 2023-06-28 16:44
Thanx for the tip

**Comment by jbadeau** [comment] 2023-06-28 16:45
Locally this issue won’t usually occur because one does not usually delete the local .m2 repo. In gitlab however; the m2 is empty my default

**Comment by khalilou88** [comment] 2023-06-28 17:09
How about putting local repo inside the project, like this project: https://github.com/khalilou88/bluezone/blob/master/pom.xml

```
	<!-- Deploy the artifact to a project local repository -->
	<distributionManagement>
		<repository>
			<id>local-repo</id>
			<name>Local Repository</name>
            <url>file://${project.build.directory}/localrepo</url>
			<layout>default</layout>
			<uniqueVersion>false</uniqueVersion>
		</repository>
 	</distributionManagement>
```

**Comment by jbadeau** [comment] 2023-06-28 17:40
It’s already there. The fundamental issue is caching. Nx needs to know to put artifacts in the local repo but calculating the path is not possible.

**Comment by jbadeau** [comment] 2023-06-28 17:41
But we have a good workaround now

**Comment by khalilou88** [comment] 2023-07-02 14:18
@jbadeau, So to summarize, the workaround is to not cache the build target for lib projects?

**Comment by jbadeau** [comment] 2023-07-02 14:30
Yes, I copy the artifact to the local repo at the end of the build. Not really nice but it’s not too expensive.

**Comment by khalilou88** [comment] 2023-07-02 14:33
It will be expensive for a big workspace.

Do you think that creating a shared remote maven repository can solve this problem?

**Comment by jbadeau** [comment] 2023-07-14 16:24
The issue is that with distributed caching, users will not have the artifact in the local repo and the build will not put it there either. Publishing to a shared repo defeats the purpose of caching. The solution we use is faster as there is no network transfer

**Comment by jbadeau** [comment] 2023-07-14 16:25
This issue can be solved when nx supports envvar interpolation in project.json and nx.json

**Comment by jbadeau** [comment] 2023-07-31 08:03
Can close this but I don't see a way to solve this cleanly until Nx supports envvar interpolation in nx.json and project.json.

**Comment by khalilou88** [comment] 2023-08-02 22:41
@jbadeau will keep it open because it's a limitation of the plugin.

**Comment by jbadeau** [comment] 2023-09-02 15:42
A small update.

The solution:

`
jar:jar install:install
`
does not fully work as jar:jar strips out the spring boot repackaged changes


Changing to:
`
jar:jar spring-boot:repackage install:install
`
works as it repackages the jar before installing.

Not very satisfactory but still much faster than rebuilding

**Comment by ToppScorer** [comment] 2023-11-30 11:41
> This issue can be solved when nx supports envvar interpolation in project.json and nx.json. We could calculate the repo path so nx caching would place the artifacts directly in the local repo. This is similar to how it puts js output to root/dust/{projectName}

@jbadeau Can you elaborate a little bit more on this? Is it possible to somehow get in between the process of replaying the cache and also put those artifacts to the m2 repo at the appropriate locations?

**Comment by jbadeau** [comment] 2023-11-30 22:30
We use [Maven CI Friendly Versions](https://maven.apache.org/maven-ci-friendly.html)
 
Parent pom:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<project
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
>

  <modelVersion>4.0.0</modelVersion>

  <groupId>com.foo</groupId>
  <artifactId>parent</artifactId>
  <version>${revision}</version>
  <packaging>pom</packaging>

  <properties>
    <revision>0.0.0</revision>
  </properties>

</project>
```

Child pom:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<project
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
>

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.foo</groupId>
    <artifactId>parent</artifactId>
    <version>${revision}</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>child</artifactId>

</project>
```

nx.json/project.json
```json
      "build"      : {
         "executor": "@jnxplus/nx-maven:run-task",
         "outputs" : [
           "{projectRoot}/target",
           "{projectRoot}/.flattened-pom.xml",
           "{workspaceRoot}/.m2/repository/com/foo/{projectName}/0.0.0"
         ],
         "options" : {
            "task": "clean install -DskipTests=true"
         }
      },
```

0.0.0 represents source dependency for us. The local repo is located in the workspace. We bundle the app jars into an image.


If you need to publish artefacts then you need to skip caching as it needs to be built with actual version

```json
      "release"            : {
         "executor": "@jnxplus/nx-maven:run-task",
         "options" : {
            "task": "deploy -Drevision=${VERSION} -DskipTests=true -pl ../{projectRoot}"
         }
      },
```

**Comment by ToppScorer** [comment] 2023-12-01 10:01
@jbadeau Thanks for that, but I think I don't quite get it.

> The local repo is located in the workspace

Is this also being commited to git? If not, then where is the difference to the normal local m2 repository?

         
```
"outputs" : [
           "{projectRoot}/target",
           "{projectRoot}/.flattened-pom.xml",
           "{workspaceRoot}/.m2/repository/com/foo/{projectName}/0.0.0"
],
```

Why do you add the m2 folder to the cache? The artifact should already been added by adding `{projectRoot}/target`.

So the problem is basically solved by just always running install without caching?

**Comment by khalilou88** [comment] 2023-12-01 14:21
@ToppScorer libs and parent-projects should be installed into .m2, so maven multi modules works.
If you have a small project just don't cache libs and parent-projects builds.

**Comment by jbadeau** [comment] 2023-12-01 15:46
We have very large monorepo with multiple teams. We heavily use multi modules. I think we just found a way to support nx caching properly. Need to test but will post back in a bit

**Comment by khalilou88** [comment] 2023-12-01 15:54
@jbadeau 

I suggest this change:
```
      "release"            : {
         "executor": "@jnxplus/nx-maven:run-task",
         "options" : {
            "relativePath": "../{projectRoot}",
            "task": "deploy -Drevision=${VERSION} -DskipTests=true"
         }
      },
```

the generated command will be `mvn deploy -Drevision=${VERSION} -DskipTests=true -pl ../{projectRoot}`

Like this we will have both case coverd : 
-pl,--projects : Comma-delimited list of specified reactor projects to build instead of all projects. A project can be specified by [groupId]:artifactId or by its relative path

**Comment by khalilou88** [comment] 2023-12-16 19:03
@jbadeau I think now we can find a solution for this with graph v2. the idea is to add `{workspaceRoot}/.m2/repository/${projectGroupId}/{projectName}/{projectVersion}` with `createNodes` function.

we can add a variable for `repositoryLocation` too

**Comment by khalilou88** [comment] 2023-12-19 12:22
@jbadeau  @ToppScorer 
The dev is done but not published yet. To restore the cache in `.m2`  just add `'{options.outputDirLocalRepo}'` to outputs like this:
 `outputs = ['{projectRoot}/target', '{options.outputDirLocalRepo}'];`
In this case `nx-maven` will calculate `outputDirLocalRepo` and add it to the the `options` during graph generation.

We use `mvn help:effective-settings` to get `localRepositoryLocation`  and I can add an option for `localRepository` inside the workspace in the future if it's really make sens.

**Comment by jbadeau** [comment] 2023-12-19 14:30
Prettyy cool. Nice use of the new api. Im still not very sure if I really like the idea of dynamic configuration that is outside nx.json and project.json. Make sit hard to know whats going on as you cant see the configuration. Still, it def help for situations like this.

**Comment by khalilou88** [comment] 2023-12-19 14:42
@jbadeau I agree with you, this is why we need explicitly to add `'{options.outputDirLocalRepo}'` to the `project.json` unless there no `project.json`.

**Comment by khalilou88** [comment] 2023-12-19 14:44
To know the configuration, there is a command  `nx show project my_project`

**Comment by jbadeau** [comment] 2023-12-19 14:44
was more a comment about the nrwl's decision to add dynamic config. Anyway, nice fix and will make some nice speed improvements as we can now cache releases

**Comment by jbadeau** [comment] 2023-12-19 14:45
Yeah, we use that command allot

**Comment by khalilou88** [comment] 2023-12-20 13:48
@jbadeau @ToppScorer 
This feat is available in version nx-maven@0.20.0.
I close this issue.

**Comment by ToppScorer** [comment] 2023-12-22 11:59
@khalilou88 Apparently you're expecting a `build` target now in the project.json. We don't have that, as we named our targets differently because of frontend and backend separation. So now we're getting errors like this when executing a Nx command:

```
>  NX   Unable to create nodes for REDACTED/pom.xml using plugin @jnxplus/nx-maven.


     Inner Error: TypeError: Cannot read properties of undefined (reading 'outputs')
       at exports.createNodes (/REDACTED/.nx/installation/node_modules/@jnxplus/nx-maven/src/graph/create-nodes.js:22:53)
       at buildProjectsConfigurationsFromProjectPathsAndPlugins (/REDACTED/.nx/installation/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:125:29)
       at createProjectConfigurations (/REDACTED/.nx/installation/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
       at _retrieveProjectConfigurations (/REDACTED/.nx/installation/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
       at retrieveProjectConfigurations (/REDACTED/.nx/installation/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
       at processTicksAndRejections (node:internal/process/task_queues:96:5)
       at async processFilesAndCreateAndSerializeProjectGraph (/REDACTED/.nx/installation/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:140:28)
       at async getCachedSerializedProjectGraphPromise (/REDACTED/.nx/installation/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:43:16)
       at async handleRequestProjectGraph (/REDACTED/.nx/installation/node_modules/nx/src/daemon/server/handle-request-project-graph.js:12:24)
       at async handleResult (/REDACTED/.nx/installation/node_modules/nx/src/daemon/server/server.js:110:16)
```

**Comment by ToppScorer** [comment] 2023-12-22 12:11
@khalilou88 There is also another problem with the `pom.xml`s now. You're expecting them to have a `groupId` and a `version` as direct childs. When using a `parent` definition for that, this is also not working.

**Comment by khalilou88** [comment] 2023-12-22 14:39
@ToppScorer I will publish a fix

**Comment by khalilou88** [comment] 2023-12-23 14:15
@ToppScorer please use version 0.20.2 for fixes

**Comment by khalilou88** [comment] 2023-12-26 06:57
Outputs are relative to the workspaceRoot. adding `{options.outputDirLocalRepo}` is not enough. 
To make caching works, we need to add `localRepoRelativePath`  to plugin options: In this case the `localRepo` will be inside the workspace.

```
    {
      "plugin": "@jnxplus/nx-maven",
      "options": {
        "mavenRootDirectory": "nx-maven",
        "localRepoRelativePath": ".m2/repository"
      }
    }
```

**Comment by ToppScorer** [comment] 2024-01-03 08:18
@khalilou88 So it's not possible to reuse an already existing Maven repository that is outside the workspace?

**Comment by khalilou88** [comment] 2024-01-03 12:09
@ToppScorer I believe so and putting the local repo inside the workspace is the same solution as @jbadeau described here. Now this solution is a part of the plugin.

I created an issue on Nx repo, to allow absolute path for target outputs : https://github.com/nrwl/nx/issues/20961

**Comment by khalilou88** [comment] 2024-01-29 12:26
Closing this issue, because the solution is complete and using `localRepoRelativePath` is recommended.

**Closed by khalilou88** 2024-01-29 12:26 UTC
